create table [dbo].[PaySecupayBasket] (
    [PaySecupayBasketGuid] [uniqueidentifier] not null,
    [PaySecupayInitGuid] [uniqueidentifier] not null,
    [ArticleNumber] [nvarchar](100) not null,
    [Name] [nvarchar](100) null,
    [Model] [nvarchar](100) null,
    [Ean] [nvarchar](100) null,
    [Quantity] [nvarchar](50) null,
    [Price] [nvarchar](50) null,
    [Total] [nvarchar](50) null,
    [Tax] [nvarchar](50) null,
    [CreatedAt] [datetime] not null,
    [CreatedBy] [nvarchar](50) not null,
    [ChangedAt] [datetime] null,
    [ChangedBy] [nvarchar](50) null,
    [DeletedAt] [datetime] null,
    [DeletedBy] [nvarchar](50) null,
    [RowVersion] [rowversion] not null,
    primary key ([PaySecupayBasketGuid])
);
create table [dbo].[PaySecupayDeliveryAddress] (
    [PaySecupayInitGuid] [uniqueidentifier] not null,
    [Firstname] [nvarchar](100) null,
    [Lastname] [nvarchar](100) null,
    [Company] [nvarchar](100) null,
    [Street] [nvarchar](100) null,
    [Housenumber] [nvarchar](50) null,
    [Zip] [nvarchar](50) null,
    [City] [nvarchar](100) null,
    [Country] [nvarchar](100) null,
    [CreatedAt] [datetime] not null,
    [CreatedBy] [nvarchar](50) not null,
    [ChangedAt] [datetime] null,
    [ChangedBy] [nvarchar](50) null,
    [DeletedAt] [datetime] null,
    [DeletedBy] [nvarchar](50) null,
    [RowVersion] [rowversion] not null,
    primary key ([PaySecupayInitGuid])
);
create table [dbo].[PaySecupayGetTypes] (
    [PaySecupayGetTypesGuid] [uniqueidentifier] not null,
    [ApiKey] [nvarchar](50) not null,
    [ApiUrl] [nvarchar](50) not null,
    [JsonOut] [nvarchar](500) null,
    [JsonIn] [nvarchar](500) null,
    [ResponseStatus] [nvarchar](50) null,
    [ResponsePaymentTypes] [nvarchar](500) null,
    [ResponseErrors] [nvarchar](500) null,
    [CreatedAt] [datetime] not null,
    [CreatedBy] [nvarchar](50) not null,
    [ChangedAt] [datetime] null,
    [ChangedBy] [nvarchar](50) null,
    [DeletedAt] [datetime] null,
    [DeletedBy] [nvarchar](50) null,
    [RowVersion] [rowversion] not null,
    primary key ([PaySecupayGetTypesGuid])
);
create table [dbo].[PaySecupayInit] (
    [PaySecupayInitGuid] [uniqueidentifier] not null,
    [ApiUrl] [nvarchar](250) null,
    [ApiKey] [nvarchar](50) not null,
    [Demo] [nvarchar](1) null,
    [PaymentType] [nvarchar](50) null,
    [PaymentAction] [nvarchar](50) null,
    [ApiVersion] [nvarchar](50) null,
    [Amount] [bigint] not null,
    [Currency] [nvarchar](10) null,
    [UrlSuccess] [nvarchar](250) null,
    [UrlFailure] [nvarchar](250) null,
    [UrlPush] [nvarchar](250) null,
    [Shop] [nvarchar](250) null,
    [ShopVersion] [nvarchar](50) null,
    [Langauge] [nvarchar](10) null,
    [ModulVersion] [nvarchar](100) null,
    [Title] [nvarchar](50) null,
    [Firstname] [nvarchar](100) null,
    [Lastname] [nvarchar](100) null,
    [Company] [nvarchar](100) null,
    [Street] [nvarchar](max) null,
    [Housenumber] [nvarchar](50) null,
    [Zip] [nvarchar](50) null,
    [City] [nvarchar](200) null,
    [Country] [nvarchar](200) null,
    [Telephone] [nvarchar](100) null,
    [Dob] [nvarchar](50) null,
    [Email] [nvarchar](250) null,
    [Ip] [nvarchar](20) null,
    [Purpose] [nvarchar](500) null,
    [OrderId] [nvarchar](100) null,
    [Note] [nvarchar](500) null,
    [ResponseStatus] [nvarchar](50) null,
    [ResponseHash] [nvarchar](30) null,
    [ResponseIFrameUrl] [nvarchar](250) null,
    [ResponseErrors] [nvarchar](500) null,
    [JsonOut] [nvarchar](max) null,
    [JsonIn] [nvarchar](max) null,
    [CreatedAt] [datetime] not null,
    [CreatedBy] [nvarchar](50) not null,
    [ChangedAt] [datetime] null,
    [ChangedBy] [nvarchar](50) null,
    [DeletedAt] [datetime] null,
    [DeletedBy] [nvarchar](50) null,
    [RowVersion] [rowversion] not null,
    primary key ([PaySecupayInitGuid])
);
create table [dbo].[PaySecupayPush] (
    [PaySecupayPushGuid] [uniqueidentifier] not null,
    [PushUrl] [nvarchar](250) not null,
    [Referrer] [nvarchar](250) not null,
    [Hash] [nvarchar](50) null,
    [StatusId] [nvarchar](50) null,
    [StatusDescription] [nvarchar](500) null,
    [Changed] [bigint] null,
    [ChangedDate] [datetime] null,
    [PaymentStatus] [nvarchar](50) null,
    [ApiKey] [nvarchar](50) null,
    [Hint] [nvarchar](500) null,
    [Ack] [nvarchar](100) null,
    [Error] [nvarchar](250) null,
    [PostIn] [nvarchar](max) null,
    [PostOut] [nvarchar](max) null,
    [CreatedAt] [datetime] not null,
    [CreatedBy] [nvarchar](50) not null,
    [ChangedAt] [datetime] null,
    [ChangedBy] [nvarchar](50) null,
    [DeletedAt] [datetime] null,
    [DeletedBy] [nvarchar](50) null,
    [RowVersion] [rowversion] not null,
    primary key ([PaySecupayPushGuid])
);
create table [dbo].[PaySecupayStatus] (
    [PaySecupayStatusGuid] [uniqueidentifier] not null,
    [ApiKey] [nvarchar](50) not null,
    [ApiUrl] [nvarchar](50) not null,
    [Hash] [nvarchar](50) not null,
    [Status] [nvarchar](50) null,
    [Errors] [nvarchar](max) null,
    [ResponseHash] [nvarchar](50) null,
    [ResponsePaymentStatus] [nvarchar](500) null,
    [ResponseStatus] [nvarchar](50) null,
    [ResponseCreated] [datetime] null,
    [ResponseDemo] [nvarchar](50) null,
    [ResponseTransId] [nvarchar](50) null,
    [ResponseAmount] [bigint] null,
    [ResponseOpt] [nvarchar](max) null,
    [JsonOut] [nvarchar](max) null,
    [JsonIn] [nvarchar](max) null,
    [CreatedAt] [datetime] not null,
    [CreatedBy] [nvarchar](50) not null,
    [ChangedAt] [datetime] null,
    [ChangedBy] [nvarchar](50) null,
    [DeletedAt] [datetime] null,
    [DeletedBy] [nvarchar](50) null,
    [RowVersion] [rowversion] not null,
    primary key ([PaySecupayStatusGuid])
);
alter table [dbo].[PaySecupayBasket] add constraint [PaySecupayBasket_Init] foreign key ([PaySecupayInitGuid]) references [dbo].[PaySecupayInit]([PaySecupayInitGuid]) on delete cascade;
alter table [dbo].[PaySecupayDeliveryAddress] add constraint [PaySecupayDeliveryAddress_Init] foreign key ([PaySecupayInitGuid]) references [dbo].[PaySecupayInit]([PaySecupayInitGuid]);
